App/urls.py
from django.conf.urls import url

from App import views

urlpatterns=[
    url(r'^index/',views.index,name='index'),
    url(r'^userzhu/',views.user_zhuce,name='user_zhuce'),
    url(r'^userlogin/',views.user_login,name='user_login'),
    url(r'^userzhongxin/',views.user_zhongxin,name='user_zhongxin'),
    url(r'^userlogout/',views.user_logout,name='user_logout'),
    url(r'^userinfor/',views.user_infor,name='user_infor')

]

djangoviews/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^app/',include('App.urls',namespace='jiale'))
]

App/models.py
from django.db import models

# Create your models here.
class UserModel(models.Model):
    u_name = models.CharField(max_length=16,unique=True)
    u_token = models.CharField(max_length=64,unique=True)

App/views.py
import hashlib
import random

import time
from django.http import HttpResponse
from django.shortcuts import render

from App.models import UserModel


def index(request):
    print(request)
    return HttpResponse('index')


def user_zhuce(request):
    if request.method == 'GET':
        return render(request,'user_zhuce.html')
    elif request.method == 'POST':
        username = request.POST.get('username')

        user = UserModel()
        user.u_name = username
        token = genrate_token(request.META.get('REMDTE_ADDR'))
        user.u_token = token

        user.save()

        response = HttpResponse('注册成功')
        response.set_cookie('token',token)
        return response
def genrate_token(ip):
    t = time.time()
    r = random.random()

    before = str(t)+str(ip)+str(r)
    print(before)

    md5 = hashlib.md5()
    md5.update(before.encode('utf-8'))
    return md5.hexdigest()


def user_login(request):
    if request.method == 'GET':
        return render(request,'ueer_login.html')
    elif request.method == 'POST':
        username = request.POST.get('username')
        users = UserModel.objects.filter(u_name=username)

        if users.exists():
            user = users.first()
            token = genrate_token(request.META.get('REMDTE_ADDR'))
            user.u_token = token
            user.save()
            response = HttpResponse('用户登录成功')
            response.set_cookie('token',user.u_token)
            return response
        else:
            return HttpResponse('登录用户不存在')



def user_zhongxin(request):
    token = request.COOKIES.get('token')
    if not token:
        return render(request, 'user_zhongxin.html')
    else:
        user = UserModel.objects.get(u_token=token)
        username = user.u_name

        return render(request,'user_zhongxin.html',context={'username':username})


def user_logout(request):
    response = HttpResponse('退出成功')
    response.delete_cookie('token')
    return response


def user_infor(request):
    u_token = request.COOKIES.get('token')
    if not u_token:
        return HttpResponse("用户已退出")
    try:
        user = UserModel.objects.get(u_token=u_token)
        username = user.u_name
        token = user.u_token
        return render(request,'user_infor.html',{'username':username,'token':token})
    except Exception as e:
        return HttpResponse('用户已被强制下线')

templates/home.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>home</title>
</head>
<body>
<h2>欢迎回来:{{ uesrname }}</h2>

<a href="{% url 'jiale:login' %}">登录</a>
<a href="{% url 'jiale:logout' %}">退出</a>
</body>
</html>

templates/login.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>login</title>
</head>
<body>

<form action="{% url 'jiale:login' %}" method='post'>
    {% csrf_token %}
    <span>用户名:</span><input type="text" name="username" placeholder="请输入用户名">
    <hr>

    <input type="submit">
</form>

</body>
</html>

templates/ueer_login.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>用户登录</title>
</head>
<body>
<form action="{% url 'jiale:user_login' %}" method="post">
    {% csrf_token %}
    <span>用户名:</span><input type="text" name="username" placeholder="清楚收入用户名">
    <hr>
    <input type="submit">
</form>

</body>
</html>

templates/user_infor.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>用户信息</title>
</head>
<body>
<h2>用户名:{{ username }}</h2>
<h3>用户token:{{ token }}</h3>

</body>
</html>

templates/user_zhongxin.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>用户中心</title>
</head>
<body>
<h2>欢迎回来:{{ username }}</h2>
<a href="{% url 'jiale:user_infor' %}">个人信息</a>

<a href="{% url 'jiale:user_zhuce' %}">注册</a>
<a href="{% url 'jiale:user_login' %}">登录</a>
<a href="{% url 'jiale:user_logout' %}">退出</a>

</body>
</html>

templates/user_zhuce.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>用户注册</title>
</head>
<body>
<form action="{% url 'jiale:user_zhuce' %}" method="post">
    {% csrf_token %}
    <span>用户名:</span><input type="text" name="username" placeholder="清楚收入用户名">
    <hr>
    <input type="submit">
</form>
</body>
</html>